# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=200)),
                ('app_name', models.CharField(max_length=200)),
                ('version_name', models.CharField(max_length=200)),
                ('version_code', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='icons')),
                ('apk_file', models.FileField(upload_to='files')),
                ('date_upload', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
    ]
